#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class TextBlock;
                ref class Button;
                ref class ComboBox;
            }
        }
    }
}

namespace SDKTemplate
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class Scenario2_FindAvailableSourceGroups : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class Scenario2_FindAvailableSourceGroups_obj2_Bindings;
        class Scenario2_FindAvailableSourceGroups_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::Image^ PreviewImage;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ outputTextBlock;
        private: ::Windows::UI::Xaml::Controls::Button^ StartButton;
        private: ::Windows::UI::Xaml::Controls::Button^ StopButton;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ GroupComboBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SourceComboBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ FormatComboBox;
    };
}

