//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include "XamlTypeInfo.g.h"

#include "App.xaml.h"
#include "MainPage.xaml.h"
#include "Scenario2_FindAvailableSourceGroups.xaml.h"
#include "Scenario1_DisplayDepthColorIR.xaml.h"
#include "XamlBindingInfo.g.hpp"
#include "App.g.hpp"
#include "MainPage.g.hpp"
#include "Scenario2_FindAvailableSourceGroups.g.hpp"
#include "Scenario1_DisplayDepthColorIR.g.hpp"

template<typename T>
::Platform::Object^ ActivateType()
{
    return ref new T;
}

template<typename TInstance, typename TItem>
void CollectionAdd(::Platform::Object^ instance, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Append((TItem)item);
}

template<typename TInstance, typename TKey, typename TItem>
void DictionaryAdd(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Insert((TKey)key, (TItem)item);
}

template<typename T>
::Platform::Object^ FromStringConverter(::XamlTypeInfo::InfoProvider::XamlUserType^ userType, ::Platform::String^ input)
{
    return ref new ::Platform::Box<T>((T)userType->CreateEnumUIntFromString(input));
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_SourceInfos(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->SourceInfos;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_SourceGroup(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->SourceGroup;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_DisplayName(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->DisplayName;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Id(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Id;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_SourceInfo(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->SourceInfo;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Format(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Format;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_FrameSourceGroups(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->FrameSourceGroups;
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_SourceInfos(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->SourceInfos = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_SourceGroup(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->SourceGroup = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_DisplayName(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->DisplayName = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Id(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Id = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_SourceInfo(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->SourceInfo = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Format(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Format = safe_cast<TValue^>(value);
}

enum TypeInfo_Flags
{
    TypeInfo_Flags_None                 = 0x00,
    TypeInfo_Flags_IsLocalType          = 0x01,
    TypeInfo_Flags_IsSystemType         = 0x02,
    TypeInfo_Flags_IsReturnTypeStub     = 0x04,
    TypeInfo_Flags_IsBindable           = 0x08,
    TypeInfo_Flags_IsMarkupExtension    = 0x10, 
};

struct TypeInfo
{
    PCWSTR  typeName;
    PCWSTR contentPropertyName;
    ::Platform::Object^ (*activator)();
    void (*collectionAdd)(::Platform::Object^, ::Platform::Object^);
    void (*dictionaryAdd)(::Platform::Object^, ::Platform::Object^, ::Platform::Object^);
    ::Platform::Object^ (*fromStringConverter)(::XamlTypeInfo::InfoProvider::XamlUserType^, ::Platform::String^);
    int     baseTypeIndex;
    int     firstMemberIndex;
    int     firstEnumValueIndex;
    int     createFromStringIndex;
    ::Windows::UI::Xaml::Interop::TypeKind kindofType;
    unsigned int flags;
};

const TypeInfo TypeInfos[] = 
{
    //   0
    L"Object", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   1
    L"String", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   2
    L"SDKTemplate.MainPage", L"",
    &ActivateType<::SDKTemplate::MainPage>, nullptr, nullptr, nullptr,
    4, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   3
    L"SDKTemplate.FrameFormatModel", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_IsBindable | TypeInfo_Flags_None,
    //   4
    L"Windows.UI.Xaml.Controls.Page", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    2, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   5
    L"SDKTemplate.FrameSourceInfoModel", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    2, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_IsBindable | TypeInfo_Flags_None,
    //   6
    L"SDKTemplate.FrameSourceGroupModel", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    6, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_IsBindable | TypeInfo_Flags_None,
    //   7
    L"SDKTemplate.SourceGroupCollection", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    10, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_IsBindable | TypeInfo_Flags_None,
    //   8
    L"Windows.UI.Xaml.Controls.UserControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    11, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   9
    L"SDKTemplate.Scenario1_DisplayDepthColorIR", L"",
    &ActivateType<::SDKTemplate::Scenario1_DisplayDepthColorIR>, nullptr, nullptr, nullptr,
    4, // Windows.UI.Xaml.Controls.Page
    11, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  10
    L"Windows.Media.Capture.Frames.MediaFrameFormat", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    11, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  11
    L"SDKTemplate.Scenario2_FindAvailableSourceGroups", L"",
    &ActivateType<::SDKTemplate::Scenario2_FindAvailableSourceGroups>, nullptr, nullptr, nullptr,
    4, // Windows.UI.Xaml.Controls.Page
    11, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  12
    L"Windows.Media.Capture.Frames.MediaFrameSourceInfo", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    11, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  13
    L"Windows.Media.Capture.Frames.MediaFrameSourceGroup", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    11, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  14
    L"Windows.Foundation.Collections.IVectorView`1<SDKTemplate.FrameSourceInfoModel>", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    11, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  15
    L"Windows.Foundation.Collections.IObservableVector`1<SDKTemplate.FrameSourceGroupModel>", L"",
    nullptr, &CollectionAdd<::Windows::Foundation::Collections::IObservableVector<::SDKTemplate::FrameSourceGroupModel^>, ::SDKTemplate::FrameSourceGroupModel^>, nullptr, nullptr,
    -1,
    11, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  Last type here is for padding
    L"", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1, 
    11, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_None,
};

const UINT TypeInfoLookup[] = { 
      0,   //   0
      0,   //   1
      0,   //   2
      0,   //   3
      0,   //   4
      0,   //   5
      0,   //   6
      2,   //   7
      2,   //   8
      2,   //   9
      2,   //  10
      2,   //  11
      2,   //  12
      2,   //  13
      2,   //  14
      2,   //  15
      2,   //  16
      2,   //  17
      2,   //  18
      2,   //  19
      2,   //  20
      3,   //  21
      3,   //  22
      3,   //  23
      3,   //  24
      3,   //  25
      3,   //  26
      3,   //  27
      3,   //  28
      4,   //  29
      5,   //  30
      5,   //  31
      5,   //  32
      6,   //  33
      8,   //  34
      8,   //  35
      8,   //  36
      9,   //  37
      9,   //  38
      9,   //  39
      9,   //  40
      9,   //  41
     10,   //  42
     10,   //  43
     10,   //  44
     10,   //  45
     11,   //  46
     11,   //  47
     12,   //  48
     12,   //  49
     13,   //  50
     14,   //  51
     14,   //  52
     14,   //  53
     14,   //  54
     14,   //  55
     14,   //  56
     14,   //  57
     14,   //  58
     14,   //  59
     14,   //  60
     14,   //  61
     14,   //  62
     14,   //  63
     14,   //  64
     14,   //  65
     14,   //  66
     14,   //  67
     14,   //  68
     14,   //  69
     14,   //  70
     14,   //  71
     14,   //  72
     14,   //  73
     14,   //  74
     14,   //  75
     14,   //  76
     14,   //  77
     14,   //  78
     15,   //  79
     15,   //  80
     15,   //  81
     15,   //  82
     15,   //  83
     15,   //  84
     15,   //  85
     16,   //  86
};

const TypeInfo* GetTypeInfo(::Platform::String^ typeName)
{
    auto typeNameLength = typeName->Length();
    if (typeNameLength < _countof(TypeInfoLookup) - 1)
    {
        for (UINT i = TypeInfoLookup[typeNameLength]; i < TypeInfoLookup[typeNameLength+1]; i++)
        {
            if (typeName == ::Platform::StringReference(TypeInfos[i].typeName))
            {
                return &TypeInfos[i];
            }
        }
    }
    return nullptr;
}

struct MemberInfo 
{
    PCWSTR shortName;
    ::Platform::Object^ (*getter)(::Platform::Object^);
    void (*setter)(::Platform::Object^, ::Platform::Object^);
    int typeIndex;
    int targetTypeIndex;
    bool isReadOnly;
    bool isDependencyProperty;
    bool isAttachable;
};

const MemberInfo MemberInfos[] = 
{
    //   0 - SDKTemplate.FrameFormatModel.Format
    L"Format",
    &GetReferenceTypeMember_Format<::SDKTemplate::FrameFormatModel>,
    &SetReferenceTypeMember_Format<::SDKTemplate::FrameFormatModel, ::Windows::Media::Capture::Frames::MediaFrameFormat>,
    10, // Windows.Media.Capture.Frames.MediaFrameFormat
    -1,
    false, false, false,
    //   1 - SDKTemplate.FrameFormatModel.DisplayName
    L"DisplayName",
    &GetReferenceTypeMember_DisplayName<::SDKTemplate::FrameFormatModel>,
    &SetReferenceTypeMember_DisplayName<::SDKTemplate::FrameFormatModel, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   2 - SDKTemplate.FrameSourceInfoModel.SourceInfo
    L"SourceInfo",
    &GetReferenceTypeMember_SourceInfo<::SDKTemplate::FrameSourceInfoModel>,
    &SetReferenceTypeMember_SourceInfo<::SDKTemplate::FrameSourceInfoModel, ::Windows::Media::Capture::Frames::MediaFrameSourceInfo>,
    12, // Windows.Media.Capture.Frames.MediaFrameSourceInfo
    -1,
    false, false, false,
    //   3 - SDKTemplate.FrameSourceInfoModel.SourceGroup
    L"SourceGroup",
    &GetReferenceTypeMember_SourceGroup<::SDKTemplate::FrameSourceInfoModel>,
    &SetReferenceTypeMember_SourceGroup<::SDKTemplate::FrameSourceInfoModel, ::Windows::Media::Capture::Frames::MediaFrameSourceGroup>,
    13, // Windows.Media.Capture.Frames.MediaFrameSourceGroup
    -1,
    false, false, false,
    //   4 - SDKTemplate.FrameSourceInfoModel.Id
    L"Id",
    &GetReferenceTypeMember_Id<::SDKTemplate::FrameSourceInfoModel>,
    &SetReferenceTypeMember_Id<::SDKTemplate::FrameSourceInfoModel, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   5 - SDKTemplate.FrameSourceInfoModel.DisplayName
    L"DisplayName",
    &GetReferenceTypeMember_DisplayName<::SDKTemplate::FrameSourceInfoModel>,
    &SetReferenceTypeMember_DisplayName<::SDKTemplate::FrameSourceInfoModel, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   6 - SDKTemplate.FrameSourceGroupModel.SourceInfos
    L"SourceInfos",
    &GetReferenceTypeMember_SourceInfos<::SDKTemplate::FrameSourceGroupModel>,
    &SetReferenceTypeMember_SourceInfos<::SDKTemplate::FrameSourceGroupModel, ::Windows::Foundation::Collections::IVectorView<::SDKTemplate::FrameSourceInfoModel^>>,
    14, // Windows.Foundation.Collections.IVectorView`1<SDKTemplate.FrameSourceInfoModel>
    -1,
    false, false, false,
    //   7 - SDKTemplate.FrameSourceGroupModel.SourceGroup
    L"SourceGroup",
    &GetReferenceTypeMember_SourceGroup<::SDKTemplate::FrameSourceGroupModel>,
    &SetReferenceTypeMember_SourceGroup<::SDKTemplate::FrameSourceGroupModel, ::Windows::Media::Capture::Frames::MediaFrameSourceGroup>,
    13, // Windows.Media.Capture.Frames.MediaFrameSourceGroup
    -1,
    false, false, false,
    //   8 - SDKTemplate.FrameSourceGroupModel.DisplayName
    L"DisplayName",
    &GetReferenceTypeMember_DisplayName<::SDKTemplate::FrameSourceGroupModel>,
    &SetReferenceTypeMember_DisplayName<::SDKTemplate::FrameSourceGroupModel, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   9 - SDKTemplate.FrameSourceGroupModel.Id
    L"Id",
    &GetReferenceTypeMember_Id<::SDKTemplate::FrameSourceGroupModel>,
    &SetReferenceTypeMember_Id<::SDKTemplate::FrameSourceGroupModel, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //  10 - SDKTemplate.SourceGroupCollection.FrameSourceGroups
    L"FrameSourceGroups",
    &GetReferenceTypeMember_FrameSourceGroups<::SDKTemplate::SourceGroupCollection>,
    nullptr,
    15, // Windows.Foundation.Collections.IObservableVector`1<SDKTemplate.FrameSourceGroupModel>
    -1,
    true,  false, false,
};

PCWSTR GetShortName(PCWSTR longName)
{
    PCWSTR separator = wcsrchr(longName, '.');
    return separator != nullptr ? separator + 1: longName;
}


const MemberInfo* GetMemberInfo(::Platform::String^ longMemberName)
{
    auto lastDotIndex = longMemberName->Length();
    while (true)
    {
        if (longMemberName->Data()[lastDotIndex] == '.')
        {
            const TypeInfo* pTypeInfo = GetTypeInfo(ref new ::Platform::String(longMemberName->Data(), lastDotIndex));
            const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
            if (pTypeInfo)
            {
                PCWSTR shortMemberName = GetShortName(longMemberName->Data());
                for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
                {
                    if (wcscmp(shortMemberName, MemberInfos[i].shortName) == 0)
                    {
                        return &MemberInfos[i];
                    }
                }
            }
            break;
        }
        if (lastDotIndex == 0)
        {
            break;
        }
        lastDotIndex--;
    }
    return nullptr;
}

#pragma warning(push)
#pragma warning(disable: 4691)
::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::OtherProviders::get()
{
    if(_otherProviders == nullptr)
    {
        auto otherProviders = ref new ::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>();
        _otherProviders = otherProviders;
    }
    return _otherProviders;
}
#pragma warning(pop)

::Windows::UI::Xaml::Markup::IXamlType^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlType(::Platform::String^ typeName)
{
    const TypeInfo* pTypeInfo = GetTypeInfo(typeName);
    const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
    if (pTypeInfo == nullptr || pNextTypeInfo == nullptr)
    {
        return nullptr;
    }
    else if (pTypeInfo->flags & TypeInfo_Flags_IsSystemType)
    {
        return ref new ::XamlTypeInfo::InfoProvider::XamlSystemBaseType(typeName);
    }
    else
    {
        ::XamlTypeInfo::InfoProvider::XamlUserType^ userType = ref new ::XamlTypeInfo::InfoProvider::XamlUserType(
            this, 
            ::Platform::StringReference(pTypeInfo->typeName), 
            this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L"")));
        userType->KindOfType = pTypeInfo->kindofType;
        userType->Activator = pTypeInfo->activator;
        userType->CollectionAdd = pTypeInfo->collectionAdd;
        userType->DictionaryAdd = pTypeInfo->dictionaryAdd;
        userType->FromStringConverter = pTypeInfo->fromStringConverter;
        userType->ContentPropertyName = ::Platform::StringReference(pTypeInfo->contentPropertyName);
        userType->IsLocalType = pTypeInfo->flags & TypeInfo_Flags_IsLocalType;
        userType->IsReturnTypeStub = pTypeInfo->flags & TypeInfo_Flags_IsReturnTypeStub;
        userType->IsBindable = pTypeInfo->flags & TypeInfo_Flags_IsBindable;
        userType->IsMarkupExtension = pTypeInfo->flags & TypeInfo_Flags_IsMarkupExtension;
        userType->CreateFromStringMethod = nullptr;
        int nextMemberIndex = pTypeInfo->firstMemberIndex;
        for (int i=pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
        {
            userType->AddMemberName(::Platform::StringReference(MemberInfos[i].shortName));
            nextMemberIndex++;
        }
        return userType;
    }
}

::Windows::UI::Xaml::Markup::IXamlMember^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlMember(::Platform::String^ longMemberName)
{
    ::XamlTypeInfo::InfoProvider::XamlMember^ xamlMember = nullptr;
    const MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);
    if (pMemberInfo != nullptr)
    {
        xamlMember = ref new ::XamlTypeInfo::InfoProvider::XamlMember(
            this,
            ::Platform::StringReference(pMemberInfo->shortName),
            ::Platform::StringReference(TypeInfos[pMemberInfo->typeIndex].typeName));
        xamlMember->Getter = pMemberInfo->getter;
        xamlMember->Setter = pMemberInfo->setter;
        xamlMember->TargetTypeName = pMemberInfo->targetTypeIndex >= 0 ? ::Platform::StringReference(TypeInfos[pMemberInfo->targetTypeIndex].typeName) : L"";
        xamlMember->IsReadOnly = pMemberInfo->isReadOnly;
        xamlMember->IsDependencyProperty = pMemberInfo->isDependencyProperty;
        xamlMember->IsAttachable = pMemberInfo->isAttachable;
    }
    return xamlMember;
}

